name: alice  #应用包名称
description: A new Flutter application. #应用或包的描述、简介


publish_to: 'none' # 如果您希望发布到pub.dev，请删除此行

# 下面定义应用程序的版本和内部版本号。
# 版本号是由点分隔的三个数字，如1.2.43
# 后跟一个可选的内部版本号，由+分隔。
# 在flutter中，版本和生成器号都可以被重写
# 分别通过指定--build name和--build number来生成。
# 在Android中，build name用作versionName，build number用作versionCode。
# 有关Android版本控制的详细信息，请访问 https://developer.android.com/studio/publish/versioning
# 在iOS中，build name用作CFBundleShortVersionString，build number用作CFBundleVersion。
# 有关iOS版本控制的详细信息，请访问
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0  # 应用或包的版本号 说明：版本号 x.y.z+m 其中 m 是构建版本，可以使用 --build-name/--build-number 构建参数覆盖，


environment: # 应用或包的开发环境 flutter的SDK版本在此区间 这个会影响到下面引用的插件依赖库
  sdk: ">=2.7.0 <3.0.0"  # Dart sdk版本号，多人开发中建议明确一个固定版本 当前版本 2.10.1(工具栏 Flie-Settings-language-Dart)


# pub依赖  已整体更新到当前日期（2020-9-26）的最新版本（fluttertoast、chewie暂未更新到最新版本） （flutter_html ^ 1.0.0内部依赖了flutter_svg ^ 0.17.4或^ 0.18.0）
# ^ 该箭头很重要 作为插件稳定版本可以把该箭头去掉，如果添加上，他会找environment 对应的开发环境下的所对应的Flutter Sdk编译的版本。
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:   # 国际化
    sdk: flutter
  intl: ^0.16.1  # 该软件包提供国际化和本地化功能，包括消息翻译，复数形式和性别，日期/数字格式和解析以及双向文本
  cupertino_icons: ^1.0.0  # 将Cupertino图标字体添加到应用程序中。用于iOS风格图标的CupertinoIcons类。对于1.0.0及更高版本（仅在Flutter SDK 1.22+版上可用）
  font_awesome_flutter: ^8.8.1  # font_awesome_flutter 以Flutter Icons的形式提供。提供1500个其他图标供您的应用程序使用。
  google_fonts: ^1.1.0  # 一种在Flutter应用程序中包含fonts.google.com中的字体的软件包。
  # flutter_svg: ^0.19.0   # 用于Flutter的SVG渲染和窗口小部件库，允许绘制和显示可缩放矢量图形1.1文件
  device_info: '>=0.4.2+8 <2.0.0'  # Flutter插件提供有关设备（制造商，型号等）以及运行该应用程序的Android或iOS版本的详细信息
  http: ^0.12.2  # 可组合的，多平台的，基于Future的API，用于HTTP请求。( 该软件包包含一组高级功能和类，可轻松使用HTTP资源。它是多平台的，并且支持移动设备，台式机和浏览器。)
  dio: ^3.0.10  # Dart的功能强大的Http客户端，它支持拦截器，FormData，请求取消，文件下载，超时等。
  json_annotation: ^3.1.0  # 通过`json_serializable`包支持JSON代码生成的类和辅助函数。
  url_launcher: ^5.7.8  # Flutter插件，用于在Android和iOS上启动URL。支持Web，电话，SMS和电子邮件方案(Flutter插件，用于在移动平台中启动URL。支持iOS，Android，Web，Windows，macOS和Linux。)
  photo_view: ^0.10.2  # Photo View提供了一个手势敏感的可缩放小部件。Photo View主要用于显示交互图像和SVG等其他内容。
  transparent_image: ^1.0.0  # Dart代码中的透明图像，表示为Uint8List。
  cached_network_image: ^2.3.3  # Flutter库可加载和缓存网络图像。也可以与占位符和错误小部件一起使用
  fluttertoast: ^7.0.4 # 用于Flutter的Toast库，可在单行代码中轻松创建Toast消息
  pull_to_refresh: ^1.6.2 # 提供给Flutter滚动组件的小部件可下拉刷新并上拉负载。
  flutter_html: ^1.0.2 # Flutter小部件，将静态HTML和CSS呈现为Flutter小部件
  flutter_swiper: ^1.1.6 # 最好的拍打器（轮播），具有多种布局，无限循环。与Android和iOS兼容。
  palette_generator: ^0.2.3  # Flutter软件包,用于从源图像生成调色板颜色。
  chewie: ^0.9.10 # Flutter的视频播放器，带有Cupertino和Material播放控件
  video_player: '>=0.10.12+5 <2.0.0'  # Flutter插件，用于与Android，iOS和Web上的其他Flutter小部件一起显示嵌入式视频。
  shared_preferences: '>=0.5.12 <2.0.0'  # Flutter插件，用于读写简单的键值对。包装iOS上的NSUserDefaults和Android上的SharedPreferences。
  flutter_staggered_grid_view: ^0.3.2  # Flutter交错网格视图。
  webview_flutter: ^0.3.24 # Flutter插件，可在Android和iOS上提供WebView小部件。
  marquee: ^1.6.1 # Flutter小部件，可无限滚动文本。提供许多自定义，包括自定义滚动方向，持续时间，曲线以及每轮后的暂停。
  badges: ^1.1.3 # 用于创建徽章的包。徽章可用于任何小部件的附加标记，例如，显示购物车中的许多物品。
  flare_flutter: ^2.0.6 # Rive 1. Flutter的矢量设计和运行时动画。
  rive: ^0.6.2 # Rive 2 Flutter运行时。该软件包提供了运行时功能，可用于播放并与https://rive.app上可用的Rive编辑器构建的动画进行交互
  provider: ^4.3.2+2 # Flutter  状态管理
  fl_chart: ^0.12.0  # 强大的Flutter图表库，当前支持折线图，条形图和饼图。
  flutter_rating_bar: ^3.0.1+1 # 一个简单但可完全自定义的Flutter等级栏。
  zefyr: ^0.12.0 # 干净，简约，易于协作的Flutter富文本编辑器。
  image_picker: ^0.6.7+12 # Flutter插件，用于从Android和iOS图像库中选择图像，并使用相机拍摄新照片。
  city_pickers: ^0.2.0 # 适用于城市选择器的Flutter插件
  flutter_colorpicker: ^0.3.4 # 一款受chrome devtools启发的HSV（HSB）/ HSL拾色器，以及用于您的flutter应用程序的材质拾色器
  permission_handler: ^5.0.1+1 # Flutter的权限插件。此插件提供了跨平台（iOS，Android）API来请求和检查权限。
  flutter_image_compress: ^0.7.0 # 使用本机代码（objc kotlin）压缩图像，速度更快。这个程式库可以在android / ios上运作
  package_info: '>=0.4.3 <2.0.0' # Flutter插件，用于查询有关应用程序包的信息，例如iOS上的CFBundleVersion或Android上的versionCode。
  local_auth: ^0.6.3+4  #适用于Android和iOS设备身份验证传感器的Flutter插件，例如指纹读取器和Touch ID
  gesture_password_widget: ^1.0.5  #Flutter的手势解锁小部件，支持高度自定义
  image_gallery_saver: ^1.6.7  # Flutter插件，用于将图像保存到图库，
  connectivity: ^2.0.2  # Flutter插件，用于发现Android和iOS上的网络（WiFi和移动/蜂窝）连接状态。
  battery: ^1.0.7  # Flutter插件，用于在Android和iOS上访问有关电池状态（充满，充电，放电）的信息。
  animations: ^1.1.2  # 精美的预制动画，可以轻松集成到任何Flutter应用程序中
  web_socket_channel: ^1.1.0  # WebSocket的StreamChannel包装器。提供跨平台的WebSocketChannel API，该API的跨平台实现可通过基础StreamChannel进行通信
  flutter_bmflocation: ^1.0.3  # Flutter的百度地图定位插件。该插件提供了跨平台（iOS，Android）API来请求位置
  zego_express_engine: ^1.15.0 # ZegoExpressEngine Flutter SDK是基于ZegoExpressEngine原生Android / iOS SDK的flutter插件包装，可提供实时视频和实时音频/视频服务
  zego_permission: # 即构Flutter工具插件，包含检查（摄像头、麦克风、相册）权限、授权（摄像头、麦克风、相册）操作、跳转设置页等功能。
    git:
      url: git://github.com/zegoim/zego-flutter-permission.git
      ref: master


# 说明：需要注意dependencies和dev_dependencies的区别，
# 前者的依赖包将作为APP的代码的一部分参与编译，生成最终的安装包
# 而后者的依赖包只是作为开发阶段的一些工具包，主要是用于帮助我们提供开发、测试效率，比如Flutter的自动化测试包等。
dev_dependencies: # 开发环境依赖的工具包（而不是Flutter应用本身依赖的包）
  flutter_test:
    sdk: flutter

#  flutterpluginsimple:
#    path: ./flutter_plugin_simple

  build_runner: ^1.8.1
  json_serializable: ^3.2.5


# 有关此文件的一般Dart部分的信息，请参见下页
# https://dart.dev/tools/pub/pubspec

# 以下部分是Flutter专用的 .
flutter: # 说明：版本号 x.y.z+m 其中 m 是构建版本，可以使用 --build-name/--build-number 构建参数覆盖，

  # 下一行确保应用程序中包含“材质图标”字体，以便可以使用“材质图标”类中的图标。
  uses-material-design: true

  # 注意: 由于 yaml 文件对缩进严格，所以必须严格按照每一层两个空格的方式进行缩进，此处assets前面应有两个空格。
  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/svg/
    - assets/icons/mbe/
    - assets/animations/
    - resources/images/
    - resources/images/2.0x/
    - resources/images/3.0x/
  # 要向应用程序添加资产，请添加资产部分，如下所示：
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # 图像资源可以引用一个或多个分辨率特定的“变体”，请参见
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # 有关从包依赖项添加资产的详细信息，请参见
  # https://flutter.dev/assets-and-images/#from-packages

  # 要将自定义字体添加到应用程序中，请在此“颤振”部分添加字体部分。
  # 这个列表中的每个条目都应该有一个“family”键和一个“fonts”键，其中的列表给出了字体的资产和其他描述符。
  # 例如:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # 有关包依赖项中字体的详细信息,请参见
  # https://flutter.dev/custom-fonts/#from-packages
